stages:
  train_bert:
    cmd: python src/core/train.py --max-samples 100000 --epochs 3 --batch-size 32
    deps:
      - data/raw/geo-reviews-dataset-2023.csv
      - src/core/train.py
      - configs/config.yaml
    params:
      - model.max_len
      - model.batch_size
      - model.epochs
      - model.learning_rate
      - data.max_samples
    outs:
      - models/best_model.pt
      - models/tokenizer
    metrics:
      - metrics.json:
          cache: false